# [development]
# accounts = ["alice"]

# [development.network]
# rpc-url = "http://localhost:8000/rpc"
# network-passphrase = "Standalone Network ; February 2017"
# run-locally = true

# [development.contracts]

# [development.contracts.fable_token]
# constructor_args = "--owner alice"


[development]
accounts = ["alice"]

[development.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"

[development.contracts]

[development.contracts.fable_token]
constructor_args = "--owner alice"